### ISSUE TITLE
GeckoLib breaking stuff

### ISSUE THREAD

**Issue by ThatGeometryDude** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#42] opened 2023-07-03 18:23 UTC
DO NOT CLOSE THIS! Hello,  my previous 2 bug reports were shut down because Nerdy can't understand that his code might have bugs. When I create a ranged item with a custom model for the bullet, it won't compile. If I disable the GeckoLib plugin it works fine. I have no other plugins.

**Comment by GoldenNinjaGaming** [comment] 2023-07-03 18:31
It has something to do with its renderer, something about Axis

**Comment by NerdyPuzzle** [comment] 2023-07-04 12:47
Since you were so extremely adamant about this being an issue with my plugin, I decided to look into it deeper. After finding zero issues while creating ranged items with it, I turned on the geckolib API.

And what a surprise that was, it doesn't work anymore. Turns out this is completely unrelated to my plugin's code, but rather with MCreator's inability to generate imports when 2 of the same named classes exist, and geckolib adds a class with the name "Axis".

This is not caused by the plugin, but by MCreator itself not being able to import duplicate classes. The only way to fix this is copy pasting the entirety of the ranged item renderer into the plugin and adding 1 extra line at the top. None of my code has "bugs", so I won't consider this a bug, but I'll keep the issue open. This is just a conflict between GeckoLib and MCreator.

**Comment by GoldenNinjaGaming** [comment] 2023-07-05 15:51
Alright, so it wasn't a bug, simply a conflict. (Not trying to be rude) any idea on when this will be fixed?

**Comment by NerdyPuzzle** [comment] 2023-07-05 19:49
next update

**Comment by GoldenNinjaGaming** [comment] 2023-07-14 11:33
When's that?

**Comment by PlanetSat0rn** [comment] 2023-07-27 05:46
i feel like next major update

**Comment by KlemenDEV** [comment] 2023-08-08 15:14
> This is not caused by the plugin, but by MCreator itself not being able to import duplicate classes.

When a duplicate class is present, there is no decision strategy possible. What you need to do is either:

1. Add import to the file (not an option you said for understandable reasons)
2. Use a full class name, eg java.utils.List instead of List (easy and recommended)
3. Open PR to MCreator as we have system of declaring preferred import packages (would only do if there is absolutely not possible to implement 2)

**Comment by NerdyPuzzle** [comment] 2023-08-26 15:58
fixed by copy pasting the projectile renderer template with the import

**Closed by NerdyPuzzle** 2023-08-26 15:58 UTC

**Comment by KlemenDEV** [comment] 2023-08-26 18:33
It would be better to not copy template and use fqdn for future proofing

**Comment by PlanetSat0rn** [comment] 2023-08-27 11:19
> fixed by copy pasting the projectile renderer template with the import

congratulations on fixing a issue that had basically turned my brain into a log
