### ISSUE TITLE
Procedure animations always briefly returning to idle state at regular interval

### ISSUE THREAD

**Issue by Vllaxa** [NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin#87] opened 2024-02-10 16:04 UTC
I'm using the latest version of MCreator (2023.4.52316) and the Geckolib plugin (v5.3). Procedure animations always keep briefly returning to idle state at regular intervals (very briefly switches to idle about once every 2 seconds). Even if I have a procedure animation set to constantly activate on entity tick with no requirements, and use an empty entity with no other AI to interfere or other animations other than the idle enabled, this still happens. Would appreciate any support and would be happy to give any info that could lead to a potential fix for this inexplicable issue. Best, Vlax

**Comment by NerdyPuzzle** [comment] 2024-02-10 19:56
Wait, are you trying to play an animation every tick? Or is this the case with looping animations too?

**Comment by Vllaxa** [comment] 2024-02-10 19:59
Hi, this is fully a looping animation that continuously activates each tick, but it is about a second in length

**Comment by NerdyPuzzle** [comment] 2024-02-10 20:11
I mean, did you set it to loop in blockbench, or does it play once and you're playing it every tick?

**Comment by Vllaxa** [comment] 2024-02-10 20:27
I have tried both ways, but currently have it set to loop in Blockbench plus activating continuously

**Comment by NerdyPuzzle** [comment] 2024-02-10 20:46
what minecraft version are you using?

**Comment by Vllaxa** [comment] 2024-02-10 20:47
Having the same issue on versions 1.20.1, 1.19.4, and 1.19.2

**Comment by NerdyPuzzle** [comment] 2024-02-10 20:50
1.19.2 is no longer supported and looping animations don't work on that. In newer versions, animations set to looping in blockbench only need to be played once to loop. If that happens when you play it once in 1.19.4 or 1.20.1 come back here and report it.

**Comment by Vllaxa** [comment] 2024-02-10 21:01
Yes, it happens identically in all of these versions. It would be hard to only play these animations once due to them being triggered continuously with parameters like another entity being nearby

**Comment by Vllaxa** [comment] 2024-02-10 21:17
Ah, thanks for the confirmation. This could be causing the issue, but in some other cases it was working.

**Comment by Vllaxa** [comment] 2024-02-10 21:26
I’ve just added a condition to only trigger the animation if it is not already playing, and the problem is still exactly the same :/

**Comment by NerdyPuzzle** [comment] 2024-02-10 23:19
the procedure block for checking if animations are playing is only clientside so not very reliable for tick triggers. you need to do it differently.

**Comment by Vllaxa** [comment] 2024-02-11 00:17
Will try to find another way, thanks

**Comment by Vllaxa** [comment] 2024-02-13 13:32
I've found a solution - the exact same procedures work without causing this issue if they're in a separate globally triggered procedure rather than the entity-specific tick procedure.

**Comment by Vllaxa** [comment] 2024-02-13 13:53
Never mind, this worked for one entity but not the other

**Comment by NerdyPuzzle** [comment] 2024-07-18 17:58
cannot reproduce. so im closing this for now unless others report the same thing.

**Closed by NerdyPuzzle** 2024-07-18 17:58 UTC
